# Generated by Django 5.1.2 on 2024-11-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_list', to='jipange.member'),
        ),
    ]
