# Generated by Django 5.1.4 on 2024-12-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipange', '0003_event_alter_contribution_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contributions_list', to='jipange.event'),
        ),
    ]
