# Generated by Django 5.1.4 on 2024-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipange', '0004_contribution_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mtaa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
