# Generated by Django 5.1.4 on 2025-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jipange', '0005_member_contact_member_mtaa_member_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
